ActiveConfig: Prod
Dev:
        ElasticSearch:
                Host: localhost
                Port: 443
                AccessKeyID: AKIAIU2775NMJ62A42DQ
                AccessKey: A9dBxX9QOKt3nGAxB9dOllTIbZ9FMKnVDQfieSd/
                Region: ap-southeast-1
                Index: goldbell
        Lambda:
                AccessKeyID: AKIAIU2775NMJ62A42DQ
                AccessKey: A9dBxX9QOKt3nGAxB9dOllTIbZ9FMKnVDQfieSd/
                Region: ap-southeast-1
        Enrich:
                SearchRadius: 100
                Database:
                        Host: localhost
                        DatabaseName: sgosm
                        UserName: postgres
                        Password: start123
        VehicleScore:
                #Time Interval between each signal recival (seconds)
                SignalInterval: 30
                DateFormat: "%Y-%m-%d"
                StartTime: T00:00:00+00:00
                EndTime: T23:59:59+00:00
                MinActiveTime: 0.1 #(6min/1hr)
Prod:
        ElasticSearch:
                Host: search-fleetman-csm6rqcgdmcambabbhqpxyrdpm.ap-southeast-1.es.amazonaws.com
                Port: 443
                AccessKeyID: AKIAIU2775NMJ62A42DQ
                AccessKey: A9dBxX9QOKt3nGAxB9dOllTIbZ9FMKnVDQfieSd/
                Region: ap-southeast-1
                Index: goldbell
        Lambda:
                AccessKeyID: AKIAIU2775NMJ62A42DQ
                AccessKey: A9dBxX9QOKt3nGAxB9dOllTIbZ9FMKnVDQfieSd/
                Region: ap-southeast-1
        Enrich:
                SearchRadius: 100
                Database:
                        Host: sgosm.caldgclf7agi.ap-southeast-1.rds.amazonaws.com
                        DatabaseName: sgosm
                        UserName: postgres
                        Password: start123
        VehicleScore:
                #Time Interval between each signal recival (seconds)
                SignalInterval: 30
                DateFormat: "%Y-%m-%d"
                StartTime: T00:00:00+00:00
                EndTime: T23:59:59+00:00
                MinActiveTime: 0.1 #(6min/1hr)
