#TABLE_NAME
      #-fieldname: ES data type
      
APPUSER:
      - UserName: keyword
      - Password: keyword
      
APPUSER_VEHICLE:
      - UserName: keyword 
      - VehicleID: integer

PARTNER:
      - PartnerName: keyword
      - APIAccessCode: keyword

VEHICLE:
      - VehicleID: integer
      - RegistrationNo: keyword 
      - Details: keyword
      - VehicleType: keyword
      - OwnerName: keyword
      - APIAccessCode: keyword
      - LinkedToAccount: keyword #indicates if the vehicle is still linked to the account 
      - Lat: float #last known coordinates
      - Lon: float
      - Pos: geo_point
      - Speed: float
      - Direction: float
      - RoadName: keyword
      - RoadType: keyword
      - SpeedLimit: float
      - OverSpeed: float
      #- State: object
      - DeviceTS: date #timestamp of the last data pull
      
POSITION:
      - VehicleID: integer 
      - DeviceTS: date
      - Lat: float
      - Lon: float
      - Pos: geo_point
      - Speed: float
      - Direction: float
      - State: object
      - Events: object
      - RoadName: keyword
      - RoadType: keyword
      - SpeedLimit: float
      - OverSpeed: float

EVENT:
      - VehicleID: integer 
      - DeviceTS: date
      - Events: object
       
VEHICLE_SCORE:
      - Date: date
      - VehicleID: integer
      - RegistrationNo: keyword
      - GPSPoints: integer
      - EngineOnPoints: integer
      - EngineOffPoints: integer
      - IdlingPoints: integer
      - MovingPoints: integer
      - OverSpeedCount: integer
      - OverSpeedFrequency: integer
      - MaxSpeed: float
      - AverageSpeed: float
      - IdlingProportion: float
      - EngineOffProportion: float
      - EstimatedDrivingTime: float
      - EstimatedDrivingDistance: float
      - Score: float